In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
csvpath = '/home/monster/Downloads/kaggle/AV-L&T-loan/ensb_csvs'
csv_list = os.listdir(csvpath)

In [3]:
csv_list

['472_61752_us_sub1_Uqjh0HH.csv',
 '472_61752_us_sub1_luiZ9Lt.csv',
 '472_61752_us_sub1.csv',
 '472_61752_us_sub1_uIXvq2B.csv',
 '472_61752_us_sub1_vHyep6e.csv',
 '472_61752_us_ens_1_Dw0KAyv.csv',
 '472_61752_us_sub1_Guk1iCB.csv',
 '472_61752_us_sub1_guGfzAZ.csv',
 '472_61752_us_sub1_pL8bYVX.csv',
 '472_61752_us_sub1_2EcpbN6.csv',
 '472_61752_us_sub1_3v9hPWK.csv',
 '472_61752_us_sub1_9GVyrsr.csv',
 '472_61752_us_sub1_ObTnt98.csv',
 '472_61752_us_ens_1_pctrQtR.csv']

In [4]:
df = pd.DataFrame()
for i, name in enumerate(csv_list):
    tmpdf = pd.read_csv(csvpath+'/'+name)
    tmpdf.columns = ['UniqueID_'+str(i), 'loan_default_'+str(i)]
    df = pd.concat([df,tmpdf],axis=1)

In [5]:
df.shape

(112392, 28)

In [6]:
df.columns

Index(['UniqueID_0', 'loan_default_0', 'UniqueID_1', 'loan_default_1',
       'UniqueID_2', 'loan_default_2', 'UniqueID_3', 'loan_default_3',
       'UniqueID_4', 'loan_default_4', 'UniqueID_5', 'loan_default_5',
       'UniqueID_6', 'loan_default_6', 'UniqueID_7', 'loan_default_7',
       'UniqueID_8', 'loan_default_8', 'UniqueID_9', 'loan_default_9',
       'UniqueID_10', 'loan_default_10', 'UniqueID_11', 'loan_default_11',
       'UniqueID_12', 'loan_default_12', 'UniqueID_13', 'loan_default_13'],
      dtype='object')

In [7]:
df.drop(['UniqueID_1','UniqueID_2','UniqueID_3','UniqueID_4', 'UniqueID_5','UniqueID_6',
 'UniqueID_7','UniqueID_8','UniqueID_9','UniqueID_10','UniqueID_11','UniqueID_12','UniqueID_13'],axis=1, inplace=True)

In [8]:
df.columns = ['UniqueID', 'loan_default_0', 'loan_default_1', 'loan_default_2',
       'loan_default_3', 'loan_default_4', 'loan_default_5', 'loan_default_6',
       'loan_default_7', 'loan_default_8', 'loan_default_9', 'loan_default_10',
       'loan_default_11','loan_default_12','loan_default_13']

In [9]:
df.head()

,UniqueID,loan_default_0,loan_default_1,loan_default_2,loan_default_3,loan_default_4,loan_default_5,loan_default_6,loan_default_7,loan_default_8,loan_default_9,loan_default_10,loan_default_11,loan_default_12,loan_default_13
0,655269,0.249950,0.239905,0.285761,0.254617,0.255028,0.249638,0.237593,0.215195,0.270294,0.285167,0.233182,0.245257,0.223704,0.249638
1,723482,0.321566,0.298171,0.283668,0.277094,0.223987,0.297701,0.308409,0.291419,0.342936,0.279660,0.290197,0.327151,0.328150,0.297701
2,758529,0.319992,0.304383,0.284000,0.276977,0.283922,0.306109,0.340632,0.316636,0.272776,0.276794,0.325962,0.334774,0.336459,0.306109
3,763449,0.360856,0.281604,0.280243,0.237625,0.450297,0.316770,0.268908,0.322173,0.280890,0.275840,0.295350,0.379648,0.367811,0.316770
4,708663,0.338584,0.318516,0.312967,0.350365,0.250626,0.322907,0.334129,0.332543,0.358591,0.309305,0.317460,0.322349,0.329453,0.322907

In [10]:
df.corr()

,UniqueID,loan_default_0,loan_default_1,loan_default_2,loan_default_3,loan_default_4,loan_default_5,loan_default_6,loan_default_7,loan_default_8,loan_default_9,loan_default_10,loan_default_11,loan_default_12,loan_default_13
UniqueID,1.000000,0.143809,0.147503,0.030769,0.036337,0.090082,0.116198,0.148420,0.148618,0.037998,0.035297,0.146485,0.164218,0.152647,0.116198
loan_default_0,0.143809,1.000000,0.936801,0.862103,0.891655,0.896629,0.967811,0.946307,0.918954,0.929331,0.886787,0.946812,0.894171,0.885740,0.967811
loan_default_1,0.147503,0.936801,1.000000,0.836315,0.871810,0.903205,0.962249,0.923246,0.932156,0.902643,0.862004,0.954245,0.898704,0.898230,0.962249
loan_default_2,0.030769,0.862103,0.836315,1.000000,0.855449,0.824591,0.910987,0.845288,0.845818,0.890955,0.973037,0.845606,0.847701,0.801321,0.910987
loan_default_3,0.036337,0.891655,0.871810,0.855449,1.000000,0.874450,0.934254,0.894319,0.864411,0.919955,0.881143,0.876708,0.855611,0.845683,0.934254
loan_default_4,0.090082,0.896629,0.903205,0.824591,0.874450,1.000000,0.938297,0.883708,0.896391,0.876065,0.848642,0.910422,0.872748,0.867230,0.938297
loan_default_5,0.116198,0.967811,0.962249,0.910987,0.934254,0.938297,1.000000,0.957848,0.956461,0.957246,0.933258,0.966806,0.947932,0.936741,1.000000
loan_default_6,0.148420,0.946307,0.923246,0.845288,0.894319,0.883708,0.957848,1.000000,0.902449,0.929815,0.870834,0.929722,0.878387,0.874312,0.957848
loan_default_7,0.148618,0.918954,0.932156,0.845818,0.864411,0.896391,0.956461,0.902449,1.000000,0.890131,0.869313,0.931643,0.908550,0.901992,0.956461
loan_default_8,0.037998,0.929331,0.902643,0.890955,0.919955,0.876065,0.957246,0.929815,0.890131,1.000000,0.916749,0.911208,0.873434,0.857336,0.957246
loan_default_9,0.035297,0.886787,0.862004,0.973037,0.881143,0.848642,0.933258,0.870834,0.869313,0.916749,1.000000,0.870769,0.869119,0.823743,0.933258
loan_default_10,0.146485,0.946812,0.954245,0.845606,0.876708,0.910422,0.966806,0.929722,0.931643,0.911208,0.870769,1.000000,0.900696,0.896727,0.966806
loan_default_11,0.164218,0.894171,0.898704,0.847701,0.855611,0.872748,0.947932,0.878387,0.908550,0.873434,0.869119,0.900696,1.000000,0.971292,0.947932
loan_default_12,0.152647,0.885740,0.898230,0.801321,0.845683,0.867230,0.936741,0.874312,0.901992,0.857336,0.823743,0.896727,0.971292,1.000000,0.936741
loan_default_13,0.116198,0.967811,0.962249,0.910987,0.934254,0.938297,1.000000,0.957848,0.956461,0.957246,0.933258,0.966806,0.947932,0.936741,1.000000

In [17]:
summary_ave_data = df.copy().drop(['loan_default_0', 'loan_default_2',
       'loan_default_3', 'loan_default_4','loan_default_9',
       'loan_default_11','loan_default_12'],axis=1)

summary_ave_data['average'] = summary_ave_data.iloc[:,1:].mean(numeric_only=True, axis=1)
summary_ave_data.head()

,UniqueID,loan_default_1,loan_default_5,loan_default_6,loan_default_7,loan_default_8,loan_default_10,loan_default_13,average
0,655269,0.239905,0.249638,0.237593,0.215195,0.270294,0.233182,0.249638,0.242206
1,723482,0.298171,0.297701,0.308409,0.291419,0.342936,0.290197,0.297701,0.303790
2,758529,0.304383,0.306109,0.340632,0.316636,0.272776,0.325962,0.306109,0.310372
3,763449,0.281604,0.316770,0.268908,0.322173,0.280890,0.295350,0.316770,0.297495
4,708663,0.318516,0.322907,0.334129,0.332543,0.358591,0.317460,0.322907,0.329579

In [18]:
df1 = summary_ave_data[['UniqueID','average']]

In [19]:
df1.columns =['UniqueID', 'loan_default']

In [14]:
df1.to_csv('ens_3_without_corr.csv',index=False)